### ISSUE TITLE
should we split out functionality into separate repos or keep as one?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/chat#15]
while I'm not a fan of a "_mono repo_", I do see the benefit of having everything in one place... what do we think?

**Comment by melroy89** [comment]
Depending of what you mean of "everything". I like to have as much as features bundled.The end-user don't want to download 3 different repositories in order to has some basic chat. I think currently it's not (yet) the time to branch and slit into more repo's.

Worse, you already have two repos??
https://github.com/dwyl/chat/
And:
https://github.com/dwyl/hapi-socketio-redis-chat-example

I hope it's the same?

**Comment by nelsonic** [comment]
@danger89 https://github.com/dwyl/hapi-socketio-redis-chat-example is a demo app.
https://github.com/dwyl/chat/ is a re-write using a different stack. 
They are _similar_ but _this_ one is going to be more detailed.

As for splitting things out, you'll see what I mean shortly. ⌛ 😉

**Comment by nelsonic** [comment]
no longer relevant. closing.
